version: '3'

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "async"
      POSTGRES_PASSWORD: "async"
      POSTGRES_DB: "async"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db